"""Initial migration

Revision ID: 67748433d62d
Revises: 
Create Date: 2025-07-15 17:43:16.244056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67748433d62d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('team')

    # ### end Alembic commands ###
